"""Adiciona colunas de assinatura na tabela olheiros

Revision ID: 9316cbe7489c
Revises: 
Create Date: 2025-06-24 21:49:37.303792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9316cbe7489c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analises_id'), table_name='analises')
    op.drop_table('analises')
    op.add_column('olheiros', sa.Column('data_inicio_assinatura', sa.DateTime(), nullable=True))
    op.add_column('olheiros', sa.Column('data_vencimento_assinatura', sa.Date(), nullable=True))
    op.add_column('olheiros', sa.Column('status_assinatura', sa.Enum('ativa', 'inadimplente', 'cancelada', 'periodo_de_teste', name='statusassinaturaenum'), nullable=True))
    op.drop_column('olheiros', 'status')
    op.add_column('planos', sa.Column('tipo_plano', sa.String(), nullable=False))
    op.add_column('planos', sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('planos', sa.Column('duracao_dias', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_planos_nome'), table_name='planos')
    op.create_unique_constraint(None, 'planos', ['tipo_plano'])
    op.drop_column('planos', 'descricao')
    op.drop_column('planos', 'duracao_meses')
    op.drop_column('planos', 'nome')
    op.drop_column('planos', 'preco')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planos', sa.Column('preco', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('planos', sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('planos', sa.Column('duracao_meses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('planos', sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'planos', type_='unique')
    op.create_index(op.f('ix_planos_nome'), 'planos', ['nome'], unique=True)
    op.drop_column('planos', 'duracao_dias')
    op.drop_column('planos', 'valor')
    op.drop_column('planos', 'tipo_plano')
    op.add_column('olheiros', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('olheiros', 'status_assinatura')
    op.drop_column('olheiros', 'data_vencimento_assinatura')
    op.drop_column('olheiros', 'data_inicio_assinatura')
    op.create_table('analises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_olheiro', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_criacao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conteudo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_olheiro'], ['olheiros.id'], name=op.f('analises_id_olheiro_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analises_pkey'))
    )
    op.create_index(op.f('ix_analises_id'), 'analises', ['id'], unique=False)
    # ### end Alembic commands ###
